services:
  php:
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www/html
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
